In [3]:
import numpy as np

In [5]:
a=np.empty([3,4],dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
b=np.zeros([3,4],dtype=int)
print(b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
b=np.ones([3,4],dtype=int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
b=a.reshape([4,3])
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
arr=np.array([2,3,4,5,6])

In [16]:
nc=arr

In [19]:
id(nc)

1811918423216

In [20]:
nc[0]=9
print(arr)
nc#changes done in one is reflected in second array ,original array is referred in both id same

[9 3 4 5 6]


array([9, 3, 4, 5, 6])

In [22]:
v=arr.view()#uses data of original but changes are reflected,make instance as different id
v[2]=1

In [23]:
print(arr)
print(nc)
v

[9 3 1 5 6]
[9 3 1 5 6]


array([9, 3, 1, 5, 6])

In [27]:
# we use copy function if changes are not reflected
c=arr.copy()
c[2]=5
arr

array([9, 3, 1, 5, 6])

In [12]:
a=np.array([2,3,4,5,6])
b=np.array([2,3,4,5,6])
d=np.dot(a,b)

In [13]:
d

90

In [14]:
a@b#dot product

90