In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("C:/Users/akanksha goel/OneDrive/Desktop/ml r/final practicals/homeprices.csv")

In [20]:
df.bedrooms.fillna(4,inplace=True)

In [21]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [22]:
m,n = df.shape
print("No of data: ",m)
print("No of Features: ",n)

No of data:  6
No of Features:  4


In [23]:
A = np.matrix(df[['area','bedrooms','age']])

In [24]:
A=np.c_[np.ones((m,1)),A]

In [25]:
A

matrix([[1.0e+00, 2.6e+03, 3.0e+00, 2.0e+01],
        [1.0e+00, 3.0e+03, 4.0e+00, 1.5e+01],
        [1.0e+00, 3.2e+03, 4.0e+00, 1.8e+01],
        [1.0e+00, 3.6e+03, 3.0e+00, 3.0e+01],
        [1.0e+00, 4.0e+03, 5.0e+00, 8.0e+00],
        [1.0e+00, 4.1e+03, 6.0e+00, 8.0e+00]])

In [26]:
A.shape

(6, 4)

In [27]:
B = np.matrix(df.price)

In [123]:
np.linalg.inv(A.T * A)

matrix([[ 2.76592051e+01,  2.33749462e-03, -5.78346965e+00,
         -6.89768977e-01],
        [ 2.33749462e-03,  2.45145796e-06, -1.93148605e-03,
         -1.61542470e-04],
        [-5.78346965e+00, -1.93148605e-03,  2.15673924e+00,
          2.05836373e-01],
        [-6.89768977e-01, -1.61542470e-04,  2.05836373e-01,
          2.32760118e-02]])

In [28]:
B=B.reshape(-1,1)

Q = (y XT)(XT X)*-1

In [29]:
B.shape

(6, 1)

In [30]:
Q=np.dot(np.linalg.inv(np.matmul(A.T ,A)),np.matmul(A.T,B))
Q

matrix([[ 2.21323002e+05],
        [ 1.12062442e+02],
        [ 2.33888801e+04],
        [-3.23171791e+03]])

In [127]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [128]:
reg.fit(A,B)

c:\users\akanksha goel\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,
c:\users\akanksha goel\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,


LinearRegression()

In [129]:
reg.coef_

array([[    0.        ,   112.06244194, 23388.88007794, -3231.71790863]])

In [130]:
reg.intercept_

array([221323.0018654])